{{- if (eq .Values.redis.type "internal") }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "statusbay.redis" . }}"
  labels:
{{ include "statusbay.labels" . | indent 4 }}
  annotations:
{{- if .Values.redis.internal.service.annotations }}
{{ toYaml .Values.redis.internal.service.annotations | indent 4 }}
{{- end }}
{{ include "statusbay.annotations" . | indent 4 }}
spec:
{{- if .Values.redis.internal.service.type }}
  type: {{ .Values.redis.internal.service.type }}
{{- end }}
  selector:
{{ include "statusbay.matchLabels" . | indent 4 }}
    component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
{{- end -}}
