{{- if (eq .Values.database.type "internal") }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ template "statusbay.database" . }}"
  labels:
{{ include "statusbay.labels" . | indent 4 }}
  annotations:
{{- if .Values.database.internal.service.annotations }}
{{ toYaml .Values.database.internal.service.annotations | indent 4 }}
{{- end }}
{{ include "statusbay.annotations" . | indent 4 }}
spec:
{{- if .Values.database.internal.service.type }}
  type: {{ .Values.database.internal.service.type }}
{{- end }}
  selector:
{{ include "statusbay.matchLabels" . | indent 4 }}
    component: database
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
{{- end -}}
