name: Go
on: [push]
jobs:

  spectralops:
    name: Spectral
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install
        run: curl -L spectralops.io/get | sudo sh
      - name: Scan
        run: spectral run
